// KAR-091 v2 — expanded harm classifier, built and tested against the REAL corpus.
const KAR091_HARM_PATTERNS = [
  ['infidelity', /\b(adulter\w*|unfaithful|infidel\w*|others['\u2019]?\s+spouse|spouses?\s+of\s+others|other['\u2019]?s?\s+spouses?|deviates? from normal sexual|illicit relation|paramour|philander\w*|illegitimate|concubine|born out of wedlock|child by another|conceived by another|secretly born to the spouse|not biologically the native|biological seed|extra-?marital affair\w*|child with an unmarried|pregnant at marriage|intimate relations with (a number|many|several)|several spouses|multiple spouses|hostile to (the )?mother|hostile to (the )?father)/i],
  ['deception', /\b(liar|cheat\w*|deceit\w*|deceiv\w*|untruthful|dishonest|fraud\w*|treacherous|informer|manipulat\w*|swindl\w*|forger\w*|traitor|hypocri\w*|talebearer|be-?fool\w*|befool\w*)\b/i],
  ['childlessness', /\b(childless|barren|loss of (a )?(child(ren)?|progeny)|bereft of (children|progeny)|bereft of (wife|spouse|husband)( and children)?|no (children|progeny|issue)\b|without (children|issue|progeny)|denied (children|progeny|issue)|destruction of (children|progeny)|death of (a )?(child|son|daughter)|deprived of (children|progeny|family life)|last in (their |the )?(family )?lineage)/i],
  ['child_sex_prediction', /\b(male child(ren)?|female child(ren)?|sex of the (child|children)|will (beget|have) (sons|daughters)|beget (sons|daughters)|more (sons|daughters)|only (sons|daughters)|many (sons|daughters)|blessed with many (sons|daughters))\b/i],
  ['reproductive_health', /\b(steril\w*|infertil\w*|miscarriage|abortion|impoten\w*|fertility (issue|problem)|unable to conceive)\b/i],
  ['medical', /\b(disease[ds]?|illness|lepros\w*|leprosy|afflicted with|blind\w*|consumption|ailment|diseased|insan\w*|tubercul\w*|epilep\w*|seizure\w*|cancer\w*|tumou?r\w*|ulcer\w*|paralys\w*|fever|jaundice|piles|fistula|asthma|diabet\w*|heart (disease|ailment)|hemorrhoid\w*|haemorrhoid\w*|hair loss|baldness|bald\b|swelling in the (testicles|groin|genitals)|testicle\w*|hydrocele|venereal|urinary (trouble|disorder|disease)|sickly|weak constitution|emaciated|bad health|damaged or problematic teeth|wound\w*|scarred|cutaneous|eruption\w*|blood disorder\w*|skin (disease|disorder|eruption)\w*)\b/i],
  ['mental_health', /\b(psychosis|psychotic|paranoi\w*|delusion\w*|depression|depressive|dissociat\w*|schizophreni\w*|mental (disorder|illness|instabilit\w*)|anxiety disorder|mania|manic|nervous breakdown|hysteria|hysteric\w*|extreme emotional instability|emotionally unstable|numbness of mind|loses balance of mind|perverted mind|mentally perturbed|perturbed mind|mentally imbalanc\w*)\b/i],
  ['disability', /\b(deformed|deformit\w*|disabled|disabilit\w*|dumb|dumbness|speechless|mute\b|stammer\w*|impaired|impairment|lame\b|crippl\w*|deaf\w*|maimed|hunchback|one-eyed|sightless|defective vision|loss of (a )?(limb|eye|sight|hearing|speech)|amputat\w*|ear (problem|complaint|trouble)\w*|ear disorder\w*|hearing complaint\w*|short of hearing|squint\w*|weak sight|whispering voice|disorder in the (right |left )?ear|harm to the (left |right )?eye|hearing (problem|complaint|loss)|blind\w*|dwarf\w*|unusually short stature|defective (of )?(a )?limb|defective hearing|eye (health|injur\w*)|(right|left) eye|lackluster eyes|eye sensitivit\w*)\b/i],
  ['addiction', /\b(addict\w*|alcohol\w*|intoxicat\w*|drunk\w*|inebriat\w*|gambl\w*|substance (abuse|dependen))\b/i],
  ['mortality', /\b(death|dies?\b|dead\b|short-?lived|short life|widow\w*|premature (death|end)|loss of life|fatal|killed|perish\w*|longevity (is )?(short|weak|reduced)|danger to life|threat to life|early (end|demise)|demise|life ?span|bereft of both parents|to (one hundred|\d{2,3}) years of age|lives? (to|for|up to) (one hundred|\d{2,3}) years|scorpion|venomous|snake ?bite|threat to the newborn|balarishta|survives infancy|exceptionally long life|mahadirghayu|end of the world)\b/i],
  ['violence_or_crime', /\b(murder\w*|cruel\w*|criminal\w*|kill\w*|violen\w*|assault\w*|robber\w*|thief|thiev\w*|antisocial|homicid\w*|felon\w*|arson\w*|torture\w*|brutal\w*|terrorist|assassin|dacoit|plunder\w*|poison\w*|annihilat\w*)\b/i],
  ['sexual_taboo_claim', /\b(incest\w*|incestuous|attraction toward the mother|attraction toward the father|sexual relations with (a )?(relative|sibling|mother|father)|bestial\w*|lust\b|libidinous|lustful)\b/i],
['progeny_prediction', /\b(legitimately one['\u2019]s own|a child (will|might) be adopted|will adopt a|child born to the spouse|only one child\b|a child is born in the \d+|child (is )?born (in|at) the \d+|born in the \d+(st|nd|rd|th)[ ,].{0,20}year|indicator of adoption|two mothers and two fathers|only one (sister|brother)|no younger siblings|very few siblings|seven brothers|among twelve siblings|born (first|second|third|fourth|fifth|last) among)\b/i],
['bodily_mark_prediction', /\b(mark on the (forehead|left arm|left ear|right arm|body)|will (acquire|have) a mark)\b/i],
  ['self_harm', /\b(suicid\w*|self-?harm|takes? (his|her|their) own life|ends? (his|her|their) (own )?life|self-?destruct\w*)\b/i],
  ['confinement_or_legal_risk', /\b(imprison\w*|incarcerat\w*|confinement|confined|jail\w*|captiv\w*|underground confinement|bondage|legal (jeopardy|trouble|proceedings)|litigation)\b/i],
  ['identity_or_gendered_claim', /\b(eunuch|gender-non-conforming|impotent man|neither man nor woman|third sex|effeminate|hermaphrodite|behaves like a (eunuch|woman|man)|unconventional (sexual )?preferences)\b/i],
  ['stigmatizing_status_claim', /\b(beggar|begging|beg for|pauper|servile|servant\b|poor servant|base-born|low(-| )?born|outcast|low social|low caste|menial|wretched|despised (by society)?|of low birth|destitute|destitution|illiterate|penury|poverty\w*|poverty-stricken|abject poverty|poor\b|sinful|sinner\w*|heinous|shameless|heretic\w*|foolish|unemployed|bereft of intelligence|lacking in intelligence|hates the (mother|father)|dislikes or hates|birth race|perverted|wicked\w*|deprav\w*|vile\b|degraded life|humiliat\w*|base acts|indulges in base|immoral\w*|begg\w*|miserly|greedy|mean nature|highly covetous|covetous|jealous of others|tattered clothes|asymmetrical body|wastes money on women)\b/i],
];

// High-risk sentinel for the build-time audit: any severe-topic word. If a
// result matches this but classifies harmful:false, the audit fails.
const KAR091_HIGH_RISK = /\b(steril|infertil|miscarriage|abortion|impoten|epilep|seizure|cancer|tumou?r|ulcer|paralys|lepros|leprosy|blind|deaf|dumb|mute|speechless|stammer|deform|disabl|crippl|lame|maimed|sightless|hemorrhoid|haemorrhoid|baldness|hair loss|ear (problem|complaint)|hearing (problem|complaint|loss)|murder|cruel|criminal|kill|assault|violen|robber|thief|terrorist|assassin|dacoit|suicid|self-?harm|adulter|unfaithful|infidel|illegitimate|concubine|childless|barren|death|dead|widow|fatal|perish|addict|alcohol|insan|psychosis|psychotic|paranoi|delusion|depression|dissociat|schizophreni|mania|eunuch|gender-non-conforming|hermaphrodite|beggar|pauper|outcast|base-born|low(-| )?born|servile|imprison|incarcerat|confinement|jail|captiv)\b|hysteria|hysteric|emotional instability|dwarf|short stature|destitute|illiterate|penury|poverty|sinful|wicked|vile|servant|begging|incest|testicle|hydrocele|venereal|disorder in the|death of (a )?(child|son|daughter)|loss of (a )?child/i;

function kar091Classify(originalResult) {
  const text = String(originalResult || '');
  const cats = [];
  for (const [name, re] of KAR091_HARM_PATTERNS) if (re.test(text)) cats.push(name);
  return cats;
}
module.exports = { KAR091_HARM_PATTERNS, KAR091_HIGH_RISK, kar091Classify };
